version: '3.8'

services:
  portfolio:
    build: .
    container_name: harel-portfolio
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Volume optionnel pour les logs
      - portfolio-logs:/var/log/nginx
    networks:
      - portfolio-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service optionnel pour le monitoring
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: portfolio-nginx-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://portfolio:80/nginx_status
    depends_on:
      - portfolio
    networks:
      - portfolio-network
    restart: unless-stopped

volumes:
  portfolio-logs:


networks:
  portfolio-network:
    driver: bridge
